# ========== General ========== #
theme = 'gruvbox-dark-hard'
editor = "micro"
dir_editor = "nemo"

auto_check_update = false

cd_on_quit = false
shell_close_on_success = true

default_open_file_preview = true
show_select_icons = true
show_image_preview = true
show_panel_footer_info = true
file_size_use_si = false

default_directory = "."

default_sort_type = 0
sort_order_reversed = false
case_sensitive_sort = false

page_scroll_size = 0

debug = false
ignore_missing_fields = false

# ========== Style ========== #
code_previewer = 'bat'
nerdfont = true
transparent_background = true

file_preview_width = 0
enable_file_preview_border = true
sidebar_width = 18

border_top = '─'
border_bottom = '─'
border_left = '│'
border_right = '│'
border_top_left = '┌'
border_top_right = '┐'
border_bottom_left = '└'
border_bottom_right = '┘'
border_middle_left = '├'
border_middle_right = '┤'

# ========== Plugins ========== #

metadata = false # needs exiftool
enable_md5_checksum = false
zoxide_support = true

[open_with]
